### ISSUE TITLE
Create GetUserPostsController

### ISSUE THREAD

**Issue by yurihnrq** [yurihnrq/next-blog-api#21]
## Description

Create endpoint to fetch specific user posts. This endpoints should be `/users/:id/posts`.

## Tasks

- [x] Create necessary users repository method
- [x] Create necessary users services
- [x] Create necessary controller
- [x] Create necessary route
  - [x] Update api collection
  - [x] Update swagger specs
