### ISSUE TITLE
Create DTOs for users services and repository

### ISSUE THREAD

**Issue by yurihnrq** [yurihnrq/next-blog-api#22]
# Description

Improve code quality by creating DTO interfaces for users module.

## Tasks

- [x] Create DTOs interfaces for users services and repository
- [x] Refactor services and repository to use DTOs interfaces
- [x] Correct unit tests
