### ISSUE TITLE
Create reusable middleware which uses a zod schema for data validation

### ISSUE THREAD

**Issue by yurihnrq** [yurihnrq/next-blog-api#29]
# Description

Use [zod](https://github.com/colinhacks/zod) for request schemas validation using a middleware that receive an schema and use it to validate the request body.

## Tasks

Tasks for the issue.

- [x] Implement the new validation middleware that uses zod schemas
- [x] Create types and interfaces based on created schemas
- [x] Use the new validation middleware to validate body data on necessary routes
