### ISSUE TITLE
Routes for posts CRUD operations

### ISSUE THREAD

**Issue by yurihnrq** [yurihnrq/next-blog-api#3]
# Description

Create API endpoints for all CRUD operations over blog posts.

## Tasks

- [x] Create posts repository
- [x] Create posts services
- [x] Create posts controllers
- [x] Create posts router
