### ISSUE TITLE
Add user verification

### ISSUE THREAD

**Issue by yurihnrq** [yurihnrq/next-blog-api#32]
## Description

Send verification e-mail with token to user on account creation. Create and endpoint (`users\:userId\verify`) to confirm verification.
A new property should be added to the User model: `isVerified`.

## Tasks

- [ ] Create EmailProvider interface and implement it with [Nodemailer](https://nodemailer.com/about/).
- [ ] Create SendVerificationEmailService.
- [ ] Send verification e-mail at CreateUserController.
- [ ] Create `users\:userId\verify` route and VerifyUserController.
