### ISSUE TITLE
Create project dev container

### ISSUE THREAD

**Issue by yurihnrq** [yurihnrq/next-blog-api#33]
## Description

Use Fedora base image to create a development container for the project.

## Tasks

The image should be configured with

- [x] ZSH as default terminal
- [x] Spaceship prompt
- [x] Node in the latest LTS version (with yarn)
- [x] Non root user
- [x] PostgreSQL
