### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by yurihnrq** [yurihnrq/next-blog-api#6]
# Description

Create a middleware that handle all errors thrown by controllers, services and repositories.

## Tasks
- [x] Create errors model (class) following this interface:
```typescript 
interface APIError {
  status: number;
  message: string;
}
```
- [x] Create middleware that handles errors
- [x] Routes must throw APIError errors which must be catch by the middleware

**Comment by guilhermealvesc** [comment]
#24
